/**
 * Mock data from the Reddit API.
 */
module.exports = {
  kind: "Listing",
  data: {
    modhash: "",
    dist: 10,
    children: [
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "WTF",
          selftext: "",
          author_fullname: "t2_x90i4rj",
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: "Guy throws gator into lake",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/WTF",
          hidden: false,
          pwls: 1,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 140,
          hide_score: false,
          name: "t3_a1augb",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 27495,
          domain: "v.redd.it",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              fallback_url: "https://v.redd.it/te7wsphl85121/DASH_2_4_M",
              height: 480,
              width: 480,
              scrubber_media_url: "https://v.redd.it/te7wsphl85121/DASH_600_K",
              dash_url: "https://v.redd.it/te7wsphl85121/DASHPlaylist.mpd",
              duration: 17,
              hls_url: "https://v.redd.it/te7wsphl85121/HLSPlaylist.m3u8",
              is_gif: false,
              transcoding_status: "completed",
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 27495,
          approved_by: null,
          thumbnail: "https://b.thumbs.redditmedia.com/VHYxxgWwrZT5ECNgQw4PeDlmGCtLKjwtR9BfLO_Unqw.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 0,
            gid_3: 0,
          },
          post_hint: "hosted:video",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543471087,
          link_flair_type: "text",
          wls: 1,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://external-preview.redd.it/_W-9Ic0d795wZWRydI-joMlo-I9jiua6Hidw5nIhj50.png?format=pjpg&amp;auto=webp&amp;s=5515f80104640629d18f0a627e20b3c13f58d6f7",
                  width: 640,
                  height: 640,
                },
                resolutions: [
                  {
                    url:
                      "https://external-preview.redd.it/_W-9Ic0d795wZWRydI-joMlo-I9jiua6Hidw5nIhj50.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=af5fc6d430eeb0cab67f0189a24abaff9ae2c431",
                    width: 108,
                    height: 108,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/_W-9Ic0d795wZWRydI-joMlo-I9jiua6Hidw5nIhj50.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=d51a5deaf78b3be071736f9ba1c88bf705c10def",
                    width: 216,
                    height: 216,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/_W-9Ic0d795wZWRydI-joMlo-I9jiua6Hidw5nIhj50.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=92dc6ca7962f6c2e9be63bb9b78177ef7d456df7",
                    width: 320,
                    height: 320,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/_W-9Ic0d795wZWRydI-joMlo-I9jiua6Hidw5nIhj50.png?width=640&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=e5ab7572b9815372773e1e9a500d0fca7e9a67f4",
                    width: 640,
                    height: 640,
                  },
                ],
                variants: {},
                id: "gheG3LfN49q61nduD_HJu41jnoYXjskCH8Zp86w5CU0",
              },
            ],
            enabled: false,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2qh61",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a1augb",
          is_robot_indexable: true,
          report_reasons: null,
          author: "Circuit_8",
          num_crossposts: 22,
          num_comments: 1469,
          send_replies: true,
          whitelist_status: "house_only",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/WTF/comments/a1augb/guy_throws_gator_into_lake/",
          parent_whitelist_status: "house_only",
          stickied: false,
          url: "https://v.redd.it/te7wsphl85121",
          subreddit_subscribers: 5365839,
          created_utc: 1543442287,
          media: {
            reddit_video: {
              fallback_url: "https://v.redd.it/te7wsphl85121/DASH_2_4_M",
              height: 480,
              width: 480,
              scrubber_media_url: "https://v.redd.it/te7wsphl85121/DASH_600_K",
              dash_url: "https://v.redd.it/te7wsphl85121/DASHPlaylist.mpd",
              duration: 17,
              hls_url: "https://v.redd.it/te7wsphl85121/HLSPlaylist.m3u8",
              is_gif: false,
              transcoding_status: "completed",
            },
          },
          is_video: true,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "gaming",
          selftext: "",
          author_fullname: "t2_ywyc2",
          saved: false,
          mod_reason_title: null,
          gilded: 1,
          clicked: false,
          title: "The classic trio",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/gaming",
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 104,
          hide_score: false,
          name: "t3_a1b0ck",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 60558,
          domain: "i.imgur.com",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 60558,
          approved_by: null,
          thumbnail: "https://b.thumbs.redditmedia.com/HQj295qEr9tfz6MaR-LaN4Rfg58lOGFauxXIjoQQuPg.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 4,
            gid_2: 1,
            gid_3: 0,
          },
          post_hint: "image",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543472104,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://external-preview.redd.it/pUx3Xvi4NLvDQs5CXuYdLm04zGt3A93QYpLQuAHOYlM.jpg?auto=webp&amp;s=f508a4e603b25a4b749dd7c756703789ed8ef18f",
                  width: 1296,
                  height: 968,
                },
                resolutions: [
                  {
                    url:
                      "https://external-preview.redd.it/pUx3Xvi4NLvDQs5CXuYdLm04zGt3A93QYpLQuAHOYlM.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=f92076d235b094784ef2c35ac9e102e434b6cf7b",
                    width: 108,
                    height: 80,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/pUx3Xvi4NLvDQs5CXuYdLm04zGt3A93QYpLQuAHOYlM.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=ee7f77f8d6661720e7c82fe7364c8e03ef1d5fd5",
                    width: 216,
                    height: 161,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/pUx3Xvi4NLvDQs5CXuYdLm04zGt3A93QYpLQuAHOYlM.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=6a208ab1b600612622fb927117ff5eb1a98a1e4b",
                    width: 320,
                    height: 239,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/pUx3Xvi4NLvDQs5CXuYdLm04zGt3A93QYpLQuAHOYlM.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=c64aede5873929d06f00e50d429d134c6034848b",
                    width: 640,
                    height: 478,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/pUx3Xvi4NLvDQs5CXuYdLm04zGt3A93QYpLQuAHOYlM.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=69e4fdd134d87dacc27fb99f7d85b6511759d031",
                    width: 960,
                    height: 717,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/pUx3Xvi4NLvDQs5CXuYdLm04zGt3A93QYpLQuAHOYlM.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=9597ac9ceca64f271d982c600ff0d7fb092829c7",
                    width: 1080,
                    height: 806,
                  },
                ],
                variants: {},
                id: "b9VxvAF0w3vhAWUHrq-un9zO6Yast4A0Dk41npSKd7s",
              },
            ],
            enabled: true,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2qh03",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a1b0ck",
          is_robot_indexable: true,
          report_reasons: null,
          author: "MattCloudy",
          num_crossposts: 12,
          num_comments: 696,
          send_replies: true,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/gaming/comments/a1b0ck/the_classic_trio/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url: "https://i.imgur.com/Dx70irm.jpg",
          subreddit_subscribers: 19733784,
          created_utc: 1543443304,
          media: null,
          is_video: false,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "politics",
          selftext: "",
          author_fullname: "t2_2i443aec",
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title:
            "Trump accused of 'cover-up' after reportedly barring CIA director Gina Haspel from briefing Senate on Khashoggi killing",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/politics",
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 70,
          hide_score: false,
          name: "t3_a19uyt",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 15288,
          domain: "businessinsider.com",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 15288,
          approved_by: null,
          thumbnail: "https://b.thumbs.redditmedia.com/9JyCFbqXlM_BrH4Ufoqgwx-jiOD_SzNzzMp3Paabwzs.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 0,
            gid_3: 0,
          },
          post_hint: "link",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543464905,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://external-preview.redd.it/0L1rqt5HDAlAhi44RL_ZFDHaLkWqnTLvU3vDyvVCDMU.jpg?auto=webp&amp;s=733c937165ff18419dff0d0821214af514c0728c",
                  width: 1136,
                  height: 568,
                },
                resolutions: [
                  {
                    url:
                      "https://external-preview.redd.it/0L1rqt5HDAlAhi44RL_ZFDHaLkWqnTLvU3vDyvVCDMU.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c9a92c7d5cfe466f0791b6b4af6c877cdb0b30bc",
                    width: 108,
                    height: 54,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/0L1rqt5HDAlAhi44RL_ZFDHaLkWqnTLvU3vDyvVCDMU.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=b76e3c15434aa8cdfd7798e61cf714aeb940cb35",
                    width: 216,
                    height: 108,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/0L1rqt5HDAlAhi44RL_ZFDHaLkWqnTLvU3vDyvVCDMU.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=ae87855f855e0aa592bc5eeb7b7c34b8cbd74f75",
                    width: 320,
                    height: 160,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/0L1rqt5HDAlAhi44RL_ZFDHaLkWqnTLvU3vDyvVCDMU.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=905a62dad6aa633bcca4a1a98d045d8194c92b1f",
                    width: 640,
                    height: 320,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/0L1rqt5HDAlAhi44RL_ZFDHaLkWqnTLvU3vDyvVCDMU.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=fa1fb32f7043436221b77d7a70ec99c2fbec3fd3",
                    width: 960,
                    height: 480,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/0L1rqt5HDAlAhi44RL_ZFDHaLkWqnTLvU3vDyvVCDMU.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=aa35c1cdd8e99959d7ae004a09c048ba8331df88",
                    width: 1080,
                    height: 540,
                  },
                ],
                variants: {},
                id: "DcdcqD41yxWGz5UBTQyz8S-XUt_G67RttEwBsg0rw9A",
              },
            ],
            enabled: false,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2cneq",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a19uyt",
          is_robot_indexable: true,
          report_reasons: null,
          author: "SelectiveOptimism",
          num_crossposts: 2,
          num_comments: 387,
          send_replies: false,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/politics/comments/a19uyt/trump_accused_of_coverup_after_reportedly_barring/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url:
            "https://www.businessinsider.com/trump-accused-of-cover-up-after-barring-haspel-from-briefing-senate-khashoggi-killing-2018-11",
          subreddit_subscribers: 4274942,
          created_utc: 1543436105,
          media: null,
          is_video: false,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "nba",
          selftext: "",
          author_fullname: "t2_gu6cx",
          saved: false,
          mod_reason_title: null,
          gilded: 1,
          clicked: false,
          title: "[Wojnarowski] Cleveland has traded Kyle Korver to Utah, league sources tell ESPN.",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/nba",
          hidden: false,
          pwls: 6,
          link_flair_css_class: "",
          downs: 0,
          thumbnail_height: 140,
          hide_score: false,
          name: "t3_a1bmks",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: "",
          subreddit_type: "public",
          ups: 5077,
          domain: "twitter.com",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: "ccddfb4e-3feb-11e8-af69-0ec720dcbbde",
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: "Details inside",
          can_mod_post: false,
          score: 5077,
          approved_by: null,
          thumbnail: "default",
          edited: false,
          author_flair_css_class: "Lakers4",
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 1,
            gid_3: 0,
          },
          post_hint: "link",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543476170,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://external-preview.redd.it/RILncgKP7aveGgpm295J3Jh6on_MPdnQRpN2XSfk4LA.jpg?auto=webp&amp;s=cedd772239c6360c88b0a7b5eab674d5b6e32b62",
                  width: 400,
                  height: 400,
                },
                resolutions: [
                  {
                    url:
                      "https://external-preview.redd.it/RILncgKP7aveGgpm295J3Jh6on_MPdnQRpN2XSfk4LA.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=aaa771c192b16bf0cefe2e58e8a751f6d65571fd",
                    width: 108,
                    height: 108,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/RILncgKP7aveGgpm295J3Jh6on_MPdnQRpN2XSfk4LA.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=2a210f1fd5add7ff00b8b6b78220ad33a5b2a23e",
                    width: 216,
                    height: 216,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/RILncgKP7aveGgpm295J3Jh6on_MPdnQRpN2XSfk4LA.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=206aab8b95426315b18ff88beb46b07d559ff4b9",
                    width: 320,
                    height: 320,
                  },
                ],
                variants: {},
                id: "8NlD4GtqucNtbKeLhC1NYlE6vbY3AuWo9VcPbx1s9Sg",
              },
            ],
            enabled: false,
          },
          media_only: false,
          link_flair_template_id: "3238a55c-9b13-11e3-8afd-22000aa47206",
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: "Lakers",
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2qo4s",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a1bmks",
          is_robot_indexable: true,
          report_reasons: null,
          author: "AnotherDuck",
          num_crossposts: 5,
          num_comments: 981,
          send_replies: false,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: "dark",
          permalink: "/r/nba/comments/a1bmks/wojnarowski_cleveland_has_traded_kyle_korver_to/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url: "https://twitter.com/wojespn/status/1067921767652569096",
          subreddit_subscribers: 1492918,
          created_utc: 1543447370,
          media: null,
          is_video: false,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "MadeMeSmile",
          selftext: "",
          author_fullname: "t2_22zlsusn",
          saved: false,
          mod_reason_title: null,
          gilded: 1,
          clicked: false,
          title: "important",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/MadeMeSmile",
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 136,
          hide_score: false,
          name: "t3_a19rx0",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 49303,
          domain: "i.redd.it",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 49303,
          approved_by: null,
          thumbnail: "https://b.thumbs.redditmedia.com/wRY1IOkZjJYeQVjYQWtiJ4MO-8hJlT638q6fz-eXyyY.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 1,
            gid_3: 0,
          },
          post_hint: "image",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543464362,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://preview.redd.it/duwhya5uo4121.jpg?auto=webp&amp;s=d2cb48e74376fcfa7a26ea1b0c8173b0c518c62e",
                  width: 640,
                  height: 626,
                },
                resolutions: [
                  {
                    url:
                      "https://preview.redd.it/duwhya5uo4121.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c67d00574155991e999d5fc4ae6107c54bf928c7",
                    width: 108,
                    height: 105,
                  },
                  {
                    url:
                      "https://preview.redd.it/duwhya5uo4121.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=58cb9457785a1aa9e7cd713cb796a579fafda5ef",
                    width: 216,
                    height: 211,
                  },
                  {
                    url:
                      "https://preview.redd.it/duwhya5uo4121.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=9801edf138250eb62e4f27cc0a2c1a41ddeb2a14",
                    width: 320,
                    height: 313,
                  },
                  {
                    url:
                      "https://preview.redd.it/duwhya5uo4121.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=eac6c7bc7381705b625807df9f51802fd8a536bf",
                    width: 640,
                    height: 626,
                  },
                ],
                variants: {},
                id: "HFvia-0zP-962EFN30L5XDwLhn_fMjyIXhJJrDA5auE",
              },
            ],
            enabled: true,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2uqcm",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a19rx0",
          is_robot_indexable: true,
          report_reasons: null,
          author: "angelaazhao",
          num_crossposts: 1,
          num_comments: 923,
          send_replies: true,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/MadeMeSmile/comments/a19rx0/important/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url: "https://i.redd.it/duwhya5uo4121.jpg",
          subreddit_subscribers: 885627,
          created_utc: 1543435562,
          media: null,
          is_video: false,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "rarepuppers",
          selftext: "",
          author_fullname: "t2_12h3hl9u",
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: "rare pupper doing a smile",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/rarepuppers",
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 140,
          hide_score: false,
          name: "t3_a19x4h",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 14362,
          domain: "i.redd.it",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 14362,
          approved_by: null,
          thumbnail: "https://b.thumbs.redditmedia.com/4gMhbmX3cQmyb0GXpfuJ46UBpCFDitpoTBP5EgvzYHE.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 0,
            gid_3: 0,
          },
          post_hint: "image",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543465291,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: "confidence",
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://preview.redd.it/sbtshhuhr4121.jpg?auto=webp&amp;s=1d812eea4cfcf1070adedd1590e7b43beb9e9cb1",
                  width: 2448,
                  height: 3264,
                },
                resolutions: [
                  {
                    url:
                      "https://preview.redd.it/sbtshhuhr4121.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=81793d1f0784a98b42b4a0e024842e0bafc5bea6",
                    width: 108,
                    height: 144,
                  },
                  {
                    url:
                      "https://preview.redd.it/sbtshhuhr4121.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=966d03be8cdbfbd998bec0e6ed1b48361d8f38ef",
                    width: 216,
                    height: 288,
                  },
                  {
                    url:
                      "https://preview.redd.it/sbtshhuhr4121.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=625aa574b90a705345d42bf04c989a4689bf76a5",
                    width: 320,
                    height: 426,
                  },
                  {
                    url:
                      "https://preview.redd.it/sbtshhuhr4121.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=d5a919b93a8091b13f358cc4c1b22b182b24d416",
                    width: 640,
                    height: 853,
                  },
                  {
                    url:
                      "https://preview.redd.it/sbtshhuhr4121.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=4ae748d6e79154ee399167bc67f3b0d71e2e6091",
                    width: 960,
                    height: 1280,
                  },
                  {
                    url:
                      "https://preview.redd.it/sbtshhuhr4121.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=6f9bc8e1cff07bd95295302f12c5f9d0030c50df",
                    width: 1080,
                    height: 1440,
                  },
                ],
                variants: {},
                id: "h9amliuvU5-fmVwc9MnrVOR0G0ZDaB5Y1714qGc_WAY",
              },
            ],
            enabled: true,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_3b749",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a19x4h",
          is_robot_indexable: true,
          report_reasons: null,
          author: "woofbru",
          num_crossposts: 2,
          num_comments: 95,
          send_replies: true,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/rarepuppers/comments/a19x4h/rare_pupper_doing_a_smile/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url: "https://i.redd.it/sbtshhuhr4121.jpg",
          subreddit_subscribers: 1031913,
          created_utc: 1543436491,
          media: null,
          is_video: false,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "Jokes",
          selftext: "Then does having sex for free make you a non-profit whoreganisation?",
          author_fullname: "t2_16aeor",
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: "If having sex for money makes you a whore...",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/Jokes",
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: null,
          hide_score: false,
          name: "t3_a1abw8",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 12844,
          domain: "self.Jokes",
          media_embed: {},
          thumbnail_width: null,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 12844,
          approved_by: null,
          thumbnail: "self",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 2,
            gid_2: 0,
            gid_3: 0,
          },
          content_categories: null,
          is_self: true,
          mod_note: null,
          created: 1543467820,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html:
            '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Then does having sex for free make you a non-profit whoreganisation?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2qh72",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a1abw8",
          is_robot_indexable: true,
          report_reasons: null,
          author: "martidr99",
          num_crossposts: 0,
          num_comments: 243,
          send_replies: true,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/Jokes/comments/a1abw8/if_having_sex_for_money_makes_you_a_whore/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url: "https://www.reddit.com/r/Jokes/comments/a1abw8/if_having_sex_for_money_makes_you_a_whore/",
          subreddit_subscribers: 14679155,
          created_utc: 1543439020,
          media: null,
          is_video: false,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "aww",
          selftext: "",
          author_fullname: "t2_xx3dy",
          saved: false,
          mod_reason_title: null,
          gilded: 2,
          clicked: false,
          title: "Lil fox loses his fren and is completely bamboozled.",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/aww",
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 140,
          hide_score: false,
          name: "t3_a195wh",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 64081,
          domain: "v.redd.it",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              fallback_url: "https://v.redd.it/9s3nt8jhc4121/DASH_9_6_M",
              height: 1080,
              width: 896,
              scrubber_media_url: "https://v.redd.it/9s3nt8jhc4121/DASH_600_K",
              dash_url: "https://v.redd.it/9s3nt8jhc4121/DASHPlaylist.mpd",
              duration: 27,
              hls_url: "https://v.redd.it/9s3nt8jhc4121/HLSPlaylist.m3u8",
              is_gif: true,
              transcoding_status: "completed",
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 64081,
          approved_by: null,
          thumbnail: "https://b.thumbs.redditmedia.com/bTgvf5jZCMbThEWHChFafVCObXQF9sG83zL7iWrgSPQ.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 2,
            gid_3: 0,
          },
          post_hint: "hosted:video",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543460253,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://external-preview.redd.it/QSNy-OSTNAAdz5jfp1Xo3O7_3_V7Luim0XGLLpXL5nE.png?format=pjpg&amp;auto=webp&amp;s=a9da4ab1c3de1d5d8e4e4c6443278694d7acb21a",
                  width: 959,
                  height: 1156,
                },
                resolutions: [
                  {
                    url:
                      "https://external-preview.redd.it/QSNy-OSTNAAdz5jfp1Xo3O7_3_V7Luim0XGLLpXL5nE.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=f97d531aa8464a30128adcc91e4b8d9249a0cac2",
                    width: 108,
                    height: 130,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/QSNy-OSTNAAdz5jfp1Xo3O7_3_V7Luim0XGLLpXL5nE.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=fd8dbfe6bdf401d88a448aeb32a9a97f3beb0cf9",
                    width: 216,
                    height: 260,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/QSNy-OSTNAAdz5jfp1Xo3O7_3_V7Luim0XGLLpXL5nE.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=61e2152d65396b4541613a844c1d4bb638a965d2",
                    width: 320,
                    height: 385,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/QSNy-OSTNAAdz5jfp1Xo3O7_3_V7Luim0XGLLpXL5nE.png?width=640&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=3a691822a8112fdbd28d9e18b1931aa863fc757c",
                    width: 640,
                    height: 771,
                  },
                ],
                variants: {},
                id: "XDFuyt26auiLgRHzyTCJTBq1Mt9xCiOVQx0SFbPo5LM",
              },
            ],
            enabled: false,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2qh1o",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a195wh",
          is_robot_indexable: true,
          report_reasons: null,
          author: "Chris_Isur_Dude",
          num_crossposts: 32,
          num_comments: 473,
          send_replies: false,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/aww/comments/a195wh/lil_fox_loses_his_fren_and_is_completely/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url: "https://v.redd.it/9s3nt8jhc4121",
          subreddit_subscribers: 18634699,
          created_utc: 1543431453,
          media: {
            reddit_video: {
              fallback_url: "https://v.redd.it/9s3nt8jhc4121/DASH_9_6_M",
              height: 1080,
              width: 896,
              scrubber_media_url: "https://v.redd.it/9s3nt8jhc4121/DASH_600_K",
              dash_url: "https://v.redd.it/9s3nt8jhc4121/DASHPlaylist.mpd",
              duration: 27,
              hls_url: "https://v.redd.it/9s3nt8jhc4121/HLSPlaylist.m3u8",
              is_gif: true,
              transcoding_status: "completed",
            },
          },
          is_video: true,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "todayilearned",
          selftext: "",
          author_fullname: "t2_1rmrdzs",
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title:
            "TIL of James Lafayette, a former slave who acted as a double agent during the American Revolution. He was able to travel freely between American and British camps, and foiled Benedict Arnold’s plan to storm Yorktown. This led to the British surrender.",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/todayilearned",
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 140,
          hide_score: false,
          name: "t3_a1agbd",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 6522,
          domain: "biography.com",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 6522,
          approved_by: null,
          thumbnail: "https://a.thumbs.redditmedia.com/PUZjsz_NG6kIg4hI7O-DrEKcERIQzKokAfkLpjRNEy8.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 0,
            gid_3: 0,
          },
          post_hint: "link",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543468562,
          link_flair_type: "text",
          wls: 6,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://external-preview.redd.it/6VwXFb4XOYLzW4ASNoV7LJutOrRkkGvxOKWTJWOPv7g.jpg?auto=webp&amp;s=351738fe5ab9c92e2eeb487c1cd88b150aac30c9",
                  width: 1200,
                  height: 1200,
                },
                resolutions: [
                  {
                    url:
                      "https://external-preview.redd.it/6VwXFb4XOYLzW4ASNoV7LJutOrRkkGvxOKWTJWOPv7g.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=a6cf2cab4b2e1a2cf4acf300389c9c2a8fd69a27",
                    width: 108,
                    height: 108,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/6VwXFb4XOYLzW4ASNoV7LJutOrRkkGvxOKWTJWOPv7g.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=d69bfc14711d9ee617f68a7007cc945214b3ed27",
                    width: 216,
                    height: 216,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/6VwXFb4XOYLzW4ASNoV7LJutOrRkkGvxOKWTJWOPv7g.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=ce884199e380275822a3af2e1c3476a6ce0abc50",
                    width: 320,
                    height: 320,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/6VwXFb4XOYLzW4ASNoV7LJutOrRkkGvxOKWTJWOPv7g.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=31e6c19c3e11728e0e9c7781a78fcec5122d46a2",
                    width: 640,
                    height: 640,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/6VwXFb4XOYLzW4ASNoV7LJutOrRkkGvxOKWTJWOPv7g.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=0e5b94852b006a112c2c30f154e655e9440060c0",
                    width: 960,
                    height: 960,
                  },
                  {
                    url:
                      "https://external-preview.redd.it/6VwXFb4XOYLzW4ASNoV7LJutOrRkkGvxOKWTJWOPv7g.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=5fad5e1d50a6946a973a49b121d296eddc6eda61",
                    width: 1080,
                    height: 1080,
                  },
                ],
                variants: {},
                id: "Zdatpwg2UMnfgbal3NuuwMCLCV4Amgf2nWGD_Q9bJ7I",
              },
            ],
            enabled: false,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_2qqjc",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a1agbd",
          is_robot_indexable: true,
          report_reasons: null,
          author: "ohsopoor",
          num_crossposts: 0,
          num_comments: 227,
          send_replies: true,
          whitelist_status: "all_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/todayilearned/comments/a1agbd/til_of_james_lafayette_a_former_slave_who_acted/",
          parent_whitelist_status: "all_ads",
          stickied: false,
          url: "https://www.biography.com/people/james-armistead-537566",
          subreddit_subscribers: 19807275,
          created_utc: 1543439762,
          media: null,
          is_video: false,
        },
      },
      {
        kind: "t3",
        data: {
          approved_at_utc: null,
          subreddit: "BlackPeopleTwitter",
          selftext: "",
          author_fullname: "t2_23h5qzj3",
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: "It’s painfully sad how true this is",
          link_flair_richtext: [],
          subreddit_name_prefixed: "r/BlackPeopleTwitter",
          hidden: false,
          pwls: 0,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: 140,
          hide_score: false,
          name: "t3_a19ai5",
          quarantine: false,
          link_flair_text_color: "dark",
          author_flair_background_color: null,
          subreddit_type: "public",
          ups: 41487,
          domain: "i.redd.it",
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 41487,
          approved_by: null,
          thumbnail: "https://b.thumbs.redditmedia.com/6KdlgRmo5eA94QaYnDCYS0xyDQhO6t7d8ppIMkWDvNk.jpg",
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {
            gid_1: 0,
            gid_2: 0,
            gid_3: 0,
          },
          post_hint: "image",
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1543461021,
          link_flair_type: "text",
          wls: 0,
          banned_by: null,
          author_flair_type: "text",
          contest_mode: false,
          selftext_html: null,
          likes: null,
          suggested_sort: "top",
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    "https://preview.redd.it/d6ybkcwve4121.jpg?auto=webp&amp;s=649021eb69a17a8463cae0a2082fcfd7e86c2681",
                  width: 1125,
                  height: 2001,
                },
                resolutions: [
                  {
                    url:
                      "https://preview.redd.it/d6ybkcwve4121.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=8dff8e1be6e4997418e9cf58b3ece575fa10a6ce",
                    width: 108,
                    height: 192,
                  },
                  {
                    url:
                      "https://preview.redd.it/d6ybkcwve4121.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=b845df0a090bbce859225d4844911e2932d0ba15",
                    width: 216,
                    height: 384,
                  },
                  {
                    url:
                      "https://preview.redd.it/d6ybkcwve4121.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=846b81edc7f54aa72db51214031157d31aec8dac",
                    width: 320,
                    height: 569,
                  },
                  {
                    url:
                      "https://preview.redd.it/d6ybkcwve4121.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=90ae3c9f5bcc3dffdda119da85993273f9e9afd2",
                    width: 640,
                    height: 1138,
                  },
                  {
                    url:
                      "https://preview.redd.it/d6ybkcwve4121.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=23b1ef9dd6394539a8b8c333c416c1d315555ecf",
                    width: 960,
                    height: 1707,
                  },
                  {
                    url:
                      "https://preview.redd.it/d6ybkcwve4121.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=1f67cbbef83378ab26f335ec4161c2159253239d",
                    width: 1080,
                    height: 1920,
                  },
                ],
                variants: {},
                id: "VWkBqdXxqrg-FKFSHT4MPi1XCox6D1jnmF02zSKIq6I",
              },
            ],
            enabled: true,
          },
          media_only: false,
          link_flair_template_id: null,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: "t5_33x33",
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: "",
          id: "a19ai5",
          is_robot_indexable: true,
          report_reasons: null,
          author: "Helperbobby",
          num_crossposts: 2,
          num_comments: 1035,
          send_replies: true,
          whitelist_status: "no_ads",
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: "/r/BlackPeopleTwitter/comments/a19ai5/its_painfully_sad_how_true_this_is/",
          parent_whitelist_status: "no_ads",
          stickied: false,
          url: "https://i.redd.it/d6ybkcwve4121.jpg",
          subreddit_subscribers: 2456371,
          created_utc: 1543432221,
          media: null,
          is_video: false,
        },
      },
    ],
    after: "t3_a19ai5",
    before: null,
  },
};
